import type { Agent, Inquiry, Property, PropertyImage, PropertyVideo } from '@/types';

export const featuredLocalities = [
  'Gachibowli',
  'Kondapur',
  'Madhapur',
  'Miyapur',
  'Kukatpally',
  'Financial District',
  'Hitech City',
];

export const sampleAgents: Agent[] = [
  {
    id: 'agent-asha',
    name: 'Ashwin Rao',
    email: 'ashwin@hydpropertyhub.com',
    phone: '+91 91234 56789',
    whatsapp: '+919123456789',
    area_specialization: ['Gachibowli', 'Hitech City', 'Financial District'],
    profile_image: 'https://res.cloudinary.com/demo/image/upload/v1690000000/agent-ashwin.jpg',
    bio: 'Premium Hyderabad advisor with decade-long experience in luxury apartments and gated communities.',
    role: 'agent',
  },
  {
    id: 'agent-sana',
    name: 'Sana Mehta',
    email: 'sana@hydpropertyhub.com',
    phone: '+91 98765 43210',
    whatsapp: '+919876543210',
    area_specialization: ['Kondapur', 'Madhapur', 'Miyapur'],
    profile_image: 'https://res.cloudinary.com/demo/image/upload/v1690000000/agent-sana.jpg',
    bio: 'Verified local expert for tech suburbs and contemporary homes in Hyderabad.',
    role: 'agent',
  },
  {
    id: 'agent-ravi',
    name: 'Ravi Kulkarni',
    email: 'ravi@hydpropertyhub.com',
    phone: '+91 99887 66554',
    whatsapp: '+919988766554',
    area_specialization: ['Kukatpally', 'Miyapur', 'Madhapur'],
    profile_image: 'https://res.cloudinary.com/demo/image/upload/v1690000000/agent-ravi.jpg',
    bio: 'Focused on high-value investor-ready homes with trusted advisory and seamless booking.',
    role: 'agent',
  },
  {
    id: 'agent-leela',
    name: 'Leela Sharma',
    email: 'leela@hydpropertyhub.com',
    phone: '+91 90123 45678',
    whatsapp: '+919012345678',
    area_specialization: ['Gachibowli', 'Kondapur', 'Hitech City'],
    profile_image: 'https://res.cloudinary.com/demo/image/upload/v1690000000/agent-leela.jpg',
    bio: 'Luxury residential specialist with a warm approach to premium buyers.',
    role: 'agent',
  },
  {
    id: 'agent-veer',
    name: 'Veer Kapoor',
    email: 'veer@hydpropertyhub.com',
    phone: '+91 93456 78901',
    whatsapp: '+919345678901',
    area_specialization: ['Financial District', 'Kondapur', 'Hitech City'],
    profile_image: 'https://res.cloudinary.com/demo/image/upload/v1690000000/agent-veer.jpg',
    bio: 'Data-driven property advisor for investors seeking strategic Hyderabad assets.',
    role: 'agent',
  },
];

export const sampleProperties: Property[] = [
  {
    id: 'prop-001',
    title: 'Skyline Luxury 3BHK with Club Access',
    slug: 'skyline-luxury-3bhk-gachibowli',
    description: 'A premium 3BHK residence with panoramic views, designer finishes, and private concierge services close to the Financial District.',
    price: 18500000,
    property_type: 'Apartment',
    bhk: 3,
    sqft: 1800,
    locality: 'Gachibowli',
    city: 'Hyderabad',
    address_approx: 'Near Hitech City Road, Gachibowli',
    amenities: ['Clubhouse', 'Infinity Pool', 'Gym', 'Power Backup', 'Private Lounge'],
    latitude: 17.4447,
    longitude: 78.3914,
    featured: true,
    verified: true,
    status: 'approved',
    agent_id: 'agent-asha',
    furnishing: 'Furnished',
    parking: 2,
    created_at: '2025-12-01T08:15:00Z',
  },
  {
    id: 'prop-002',
    title: 'Designer 2BHK in Kondapur Tech Hub',
    slug: 'designer-2bhk-kondapur',
    description: 'An elegant 2BHK apartment with premium finishes, smart home integration, and easy access to corporate campuses.',
    price: 11200000,
    property_type: 'Apartment',
    bhk: 2,
    sqft: 1250,
    locality: 'Kondapur',
    city: 'Hyderabad',
    address_approx: 'Green Valley Road, Kondapur',
    amenities: ['Smart Lock', 'Gym', 'Rooftop Lounge', '24x7 Security'],
    latitude: 17.4482,
    longitude: 78.3832,
    featured: true,
    verified: true,
    status: 'approved',
    agent_id: 'agent-sana',
    furnishing: 'Semi-Furnished',
    parking: 1,
    created_at: '2025-11-28T09:20:00Z',
  },
  {
    id: 'prop-003',
    title: 'Grande Villa with Private Garden',
    slug: 'grande-villa-kukatpally',
    description: 'A rare premium villa with landscaped gardens, vaulted ceilings, and a serene neighborhood in Kukatpally.',
    price: 26500000,
    property_type: 'Villa',
    bhk: 4,
    sqft: 3200,
    locality: 'Kukatpally',
    city: 'Hyderabad',
    address_approx: 'West End Layout, Kukatpally',
    amenities: ['Private Garden', 'Home Theater', 'Servant Quarters', 'Solar Backup'],
    latitude: 17.4498,
    longitude: 78.3781,
    featured: true,
    verified: true,
    status: 'approved',
    agent_id: 'agent-ravi',
    furnishing: 'Unfurnished',
    parking: 3,
    created_at: '2025-11-24T10:35:00Z',
  },
  {
    id: 'prop-004',
    title: 'Executive 3BHK Near Cyber Towers',
    slug: 'executive-3bhk-hitech-city',
    description: 'Premium high-floor apartment for professionals in Hitech City, designed for executive lifestyle and workspace convenience.',
    price: 14950000,
    property_type: 'Apartment',
    bhk: 3,
    sqft: 1600,
    locality: 'Hitech City',
    city: 'Hyderabad',
    address_approx: 'Cyber Towers Road, Hitech City',
    amenities: ['Sky Deck', 'Business Lounge', 'Concierge', 'CCTV'],
    latitude: 17.4448,
    longitude: 78.3784,
    featured: false,
    verified: true,
    status: 'approved',
    agent_id: 'agent-leela',
    furnishing: 'Furnished',
    parking: 2,
    created_at: '2025-11-22T11:05:00Z',
  },
  {
    id: 'prop-005',
    title: 'Modern 2BHK in Financial District',
    slug: 'modern-2bhk-financial-district',
    description: 'A sleek 2BHK with premium interiors and easy commuting to top business parks in Hyderabad.',
    price: 13200000,
    property_type: 'Apartment',
    bhk: 2,
    sqft: 1300,
    locality: 'Financial District',
    city: 'Hyderabad',
    address_approx: 'Gandipet Road, Financial District',
    amenities: ['Business Center', 'Green Plaza', 'Swimming Pool', 'Dedicated Parking'],
    latitude: 17.4485,
    longitude: 78.3859,
    featured: true,
    verified: true,
    status: 'approved',
    agent_id: 'agent-veer',
    furnishing: 'Semi-Furnished',
    parking: 1,
    created_at: '2025-11-20T07:50:00Z',
  },
];

export const samplePropertyImages: PropertyImage[] = [
  {
    id: 'img-001',
    property_id: 'prop-001',
    image_url: 'https://res.cloudinary.com/demo/image/upload/v1690000000/property-gachibowli-1.jpg',
  },
  {
    id: 'img-002',
    property_id: 'prop-001',
    image_url: 'https://res.cloudinary.com/demo/image/upload/v1690000000/property-gachibowli-2.jpg',
  },
  {
    id: 'img-003',
    property_id: 'prop-002',
    image_url: 'https://res.cloudinary.com/demo/image/upload/v1690000000/property-kondapur-1.jpg',
  },
  {
    id: 'img-004',
    property_id: 'prop-003',
    image_url: 'https://res.cloudinary.com/demo/image/upload/v1690000000/property-kukatpally-1.jpg',
  },
  {
    id: 'img-005',
    property_id: 'prop-004',
    image_url: 'https://res.cloudinary.com/demo/image/upload/v1690000000/property-hitech-1.jpg',
  },
];

export const samplePropertyVideos: PropertyVideo[] = [
  {
    id: 'vid-001',
    property_id: 'prop-001',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 'vid-002',
    property_id: 'prop-003',
    video_url: 'https://www.youtube.com/embed/5qap5aO4i9A',
  },
];

export const sampleInquiries: Inquiry[] = [
  {
    id: 'inq-001',
    property_id: 'prop-001',
    buyer_name: 'Priya Reddy',
    buyer_phone: '+91 90000 11111',
    buyer_email: 'priya.reddy@example.com',
    message: 'Interested in a site visit this weekend. Please share availability.',
    inquiry_status: 'new',
    assigned_agent_id: 'agent-asha',
    created_at: '2025-12-02T12:24:00Z',
  },
];
